/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomImageUpload: typeof import('./components/CustomImageUpload/index.vue')['default']
    CwrsCellAvatar: typeof import('./components/CwrsCell/CwrsCellAvatar.vue')['default']
    CwrsCellImgs: typeof import('./components/CwrsCell/CwrsCellImgs.vue')['default']
    CwrsCellTag: typeof import('./components/CwrsCell/CwrsCellTag.vue')['default']
    CwrsCellTags: typeof import('./components/CwrsCell/CwrsCellTags.vue')['default']
    CwrsCodeView: typeof import('./components/CwrsCodeView/index.vue')['default']
    CwrsDot: typeof import('./components/CwrsDot/index.tsx')['default']
    CwrsEditTable: typeof import('./components/CwrsEditTable/CwrsEditTable.vue')['default']
    CwrsFooter: typeof import('./components/CwrsFooter/index.vue')['default']
    CwrsIconBox: typeof import('./components/CwrsIconBox/index.vue')['default']
    CwrsIconSelector: typeof import('./components/CwrsIconSelector/index.vue')['default']
    CwrsIframe: typeof import('./components/CwrsIframe/index.vue')['default']
    CwrsOption: typeof import('./components/CwrsOption/index.vue')['default']
    CwrsOptionItem: typeof import('./components/CwrsOptionItem/index.vue')['default']
    CwrsPageLayout: typeof import('./components/CwrsPageLayout/index.vue')['default']
    CwrsSelect: typeof import('./components/CwrsSelect/index.vue')['default']
    CwrsSpace: typeof import('./components/CwrsSpace/index.vue')['default']
    CwrsSplitButton: typeof import('./components/CwrsSplitButton/index.vue')['default']
    CwrsSplitPane: typeof import('./components/CwrsSplitPane/index.vue')['default']
    CwrsSplitPaneFlexibleBox: typeof import('./components/CwrsSplitPane/components/CwrsSplitPaneFlexibleBox.vue')['default']
    CwrsSvgIcon: typeof import('./components/CwrsSvgIcon/index.vue')['default']
    CwrsSwitch: typeof import('./components/CwrsSwitch/index.vue')['default']
    CwrsTable: typeof import('./components/CwrsTable/src/CwrsTable.vue')['default']
    CwrsTag: typeof import('./components/CwrsTag/index.tsx')['default']
    CwrsThemeBtn: typeof import('./components/CwrsThemeBtn/index.vue')['default']
    CwrsTreeSelect: typeof import('./components/CwrsTreeSelect/index.vue')['default']
    DeptTreeSelect: typeof import('./components/DeptTreeSelect/index.vue')['default']
    ElUpload: typeof import('./components/el-upload/index.vue')['default']
    GiForm: typeof import('./components/CwrsForm/src/GiForm.vue')['default']
    Icon403: typeof import('./components/icons/Icon403.vue')['default']
    Icon404: typeof import('./components/icons/Icon404.vue')['default']
    Icon500: typeof import('./components/icons/Icon500.vue')['default']
    IconBorders: typeof import('./components/icons/IconBorders.vue')['default']
    IconTableSize: typeof import('./components/icons/IconTableSize.vue')['default']
    IconTreeAdd: typeof import('./components/icons/IconTreeAdd.vue')['default']
    IconTreeReduce: typeof import('./components/icons/IconTreeReduce.vue')['default']
    Pagination: typeof import('./components/Pagination/index.vue')['default']
    ParentView: typeof import('./components/ParentView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
